<?php

namespace Fabien\EventsEngineBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{

  public function getPersons(){
    $qb = $this->createQueryBuilder('p')
        ->orderBy("p.prenom",'ASC')
        ;

    return $qb;
  }


  public function getPersonByVideosSemaine(){
    $qb = $this->createQueryBuilder('p')
        ->join("p.videos","vid")
          ->where("vid.datePublication > :semaine")
          ->setParameter("semaine",new \DateTime('now -7 days'))
          ->addSelect("count(vid) as cptvideos")
        ->join("p.image","im")
        ->groupBy("p.id")
        ->orderBy("cptvideos",'DESC')
        ->getQuery()
        ->getResult()
        ;

    return $qb;
  }


  public function findVideos($person,$date){
    $date=$date." 00:00:01";
    $qb = $this->createQueryBuilder('p')
        ->where("p = :person")
          ->setParameter("person",$person)
        ->join("p.videos","vid")
          ->andWhere("vid.dateCreation >= :limit")
          ->setParameter("limit",new \DateTime($date))
          ->addSelect("count(vid) as cptvideos")
          ->andwhere("vid.publish != :publish")
          ->setParameter('publish', false)
        ->groupBy("p.id")
        ->orderBy("cptvideos",'DESC')
        ->getQuery()
        ->getResult()
        ;

    return $qb;
  }

  public function getPersonByVideosPlusSemaine(){
    $qb = $this->createQueryBuilder('p')
        ->join("p.videos","vid")
          ->where("vid.datePublication < :semaine")
          ->setParameter("semaine",new \DateTime('now -7 days'))
          ->addSelect("count(vid) as cptvideos")
        ->join("p.image","im")
        ->groupBy("p.id")
        ->orderBy("cptvideos",'DESC')
        ->getQuery()
        ->getResult()
        ;

    return $qb;
  }


}
