<?php

namespace Fabien\EventsEngineBundle\Repository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{
  public function listStateCountry($country)
  {
  $qb = $this->createQueryBuilder('r')      
              ->where('r.country= :country')
              ->setParameter('country', $country);

  return $qb->getQuery()
            ->getArrayResult();
  }
}
