<?php

namespace Fabien\EventsEngineBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
  public function getVideos($person=null,$limit=12,$offset=0,$type=null){

    $req= $this->createQueryBuilder('v');

    if($person!=null){
      $req->join("v.persons","persons")
          ->andwhere("persons= :person")
            ->setParameter('person', $person);
    }

    if($type!=null and $type!="all"){
      $req->andwhere("v.type = :typeVideo")
          ->setParameter('typeVideo', $type);
    }

    $req->andwhere("v.publish != :publish")
        ->setParameter('publish', false);

      return $req->orderBy("v.datePublication","DESC")
          ->setMaxResults($limit)
          ->setFirstResult($offset)
          ->getQuery()
          ->getResult()
          ;


  }

  public function lastVideos($limit=4){

    return $this->createQueryBuilder('v')
            ->orderBy("v.datePublication","DESC")
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult()
            ;

  }

}
