<?php

namespace Sensio\Bundle\GeneratorBundle\Repository;

/**
 * contryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contryRepository extends \Doctrine\ORM\EntityRepository
{
}
